### ISSUE TITLE
Merge references are not correctly handled

### ISSUE THREAD

**Issue by cobalthex** [andrewlock/NetEscapades.Configuration#59]
```yml
---
defaults: &defaults
  A: 1
  B: 2
mapping:
  << : *defaults
  A: 23
  C: 99
```

should parse as
```
mapping.A = 23
mapping.B = 2
mapping.C = 99
```

but instead parses as
```
mapping.<<.A = 1
mapping.<<.B = 2
mapping.A = 23
mapping.C = 99
```
